# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Closing issues
on:
  issues:
    types:
      - closed
jobs:
  remove_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Closing issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          remove-labels: "triage, open"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
